name = "OSQP"
uuid = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
keywords = ["numerical-optimization", "solver"]
license = "Apache 2.0"
desc = "The Operator Splitting QP Solver."
repo = "https://github.com/oxfordcontrol/OSQP.jl.git"
version = "0.5.2"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BinaryProvider = "≥ 0.3.0"
MathOptInterface = "~0.8"
MathProgBase = "~0.5.0, ~0.6, ~0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[targets]
test = ["Test", "Compat"]
